variable "region_name" {}
variable "vpc_cidr_block" {}
variable "vpc_tags" {}
variable "subnet_cidr_block" {}
variable "subnet_az" {}
variable "subnet_tags" {}
variable "igw_tags" {}
variable "rt_cidr_block" {}
variable "rt_tags" {}
variable "sg_tags" {}
variable "ec2_ami" {}
variable "ec2_az" {}
variable "ec2_instance_type" {}
variable "ec2_key_name" {}
